services:
  db:
    image: postgres:12.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6432:5432"
volumes:
  db_data:
    driver: local
