version: "3"
services:
  db:
    image: postgres:12.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  redis:
    image: redis:6.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
