// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrator

import (
	"github.com/authgear/authgear-nft-indexer/pkg/config"
)

// Injectors from wire.go:

func NewMigrator(configPath string) Migrator {
	configConfig := config.NewConfig(configPath)
	migrator := Migrator{
		Config: configConfig,
	}
	return migrator
}
